before_install:
  gem install bundler
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - ruby-head
script: make
matrix:
  include:
    - rvm: jruby-9.2.5.0
      env: EXCLUDED_DIRS="activesupport-5.0.0"
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
